
server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lhptest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lee.model.Goods

swagger:
    enable: true

